# VacationPy
---

## Starter Code to Import Libraries and Load the Weather and Coordinates Data

In [1]:
# Dependencies and Setup
import hvplot.pandas
import pandas as pd
import requests
import geoviews
import numpy as np

# Import API key
from api_keys import geoapify_key

c:\Users\seyhr\anaconda3\envs\dev\lib\site-packages\paramiko\pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
c:\Users\seyhr\anaconda3\envs\dev\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
  "class": algorithms.Blowfish,
c:\Users\seyhr\anaconda3\envs\dev\lib\site-packages\paramiko\transport.py:243: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,

In [2]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
city_data_df = pd.read_csv("output_data/cities.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,bredasdorp,-34.5322,20.0403,24.07,58,90,9.48,ZA,1733484711
1,1,port lincoln,-34.7333,135.8667,21.07,82,57,1.69,AU,1733484712
2,2,port-aux-francais,-49.3500,70.2167,4.60,76,51,15.01,TF,1733484713
3,3,ta`u,-14.2336,-169.5144,27.69,81,100,6.77,AS,1733484714
4,4,blackmans bay,-43.0167,147.3167,15.07,86,85,2.20,AU,1733484715

---

### Step 1: Create a map that displays a point for every city in the `city_data_df` DataFrame. The size of the point should be the humidity in each city.

In [8]:
%%capture --no-display

# Configure the map plot
city_map = city_data_df.hvplot.points(
    x="Lng",
    y="Lat",
    size="Humidity",
    geo=True,
    tiles="OSM",
    color="City",
    width = 1000,
    height = 600,
    alpha=0.6,
    hover_cols=["City", "Country", "Humidity"])

# Display the map
city_map

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Lng,Lat]   (City,Humidity,Country)

### Step 2: Narrow down the `city_data_df` DataFrame to find your ideal weather condition

In [9]:
# Narrow down cities that fit criteria and drop any results with null values
narrowed_city_df = city_data_df.loc[
    (city_data_df["Max Temp"] < 27) & (city_data_df["Max Temp"] > 21) \
    & (city_data_df["Wind Speed"] < 4.5) \
    & (city_data_df["Cloudiness"] == 0)
]

# Drop any rows with null values
narrowed_city_df = narrowed_city_df.dropna()

# Display sample data
narrowed_city_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
22,22,east london,-33.0153,27.9116,24.52,57,0,4.12,ZA,1733484735
69,69,acapulco de juarez,16.8634,-99.8901,23.90,88,0,2.06,MX,1733484791
116,116,mukalla,14.5425,49.1242,26.60,45,0,2.45,YE,1733484832
157,157,kailua-kona,19.6406,-155.9956,22.98,68,0,1.54,US,1733484895
218,218,hafar al-batin,28.4328,45.9708,22.32,30,0,3.09,SA,1733484965
291,291,macau,22.2006,113.5461,22.06,68,0,3.60,MO,1733485047
296,296,anupgarh,29.1911,73.2086,21.89,18,0,1.82,IN,1733485053
297,297,howrah,22.5892,88.3103,26.00,38,0,2.06,IN,1733485054
348,348,saddiqabad,28.3062,70.1307,24.57,9,0,3.69,PK,1733485111

### Step 3: Create a new DataFrame called `hotel_df`.

In [4]:
# Use the Pandas copy function to create DataFrame called hotel_df to store the city, country, coordinates, and humidity
hotel_df = narrowed_city_df[["City", "Country", "Lat","Lng", "Humidity"]].copy()

# Add an empty column, "Hotel Name," to the DataFrame so you can store the hotel found using the Geoapify API
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df

                   City Country      Lat       Lng  Humidity Hotel Name
22          east london      ZA -33.0153   27.9116        57
69   acapulco de juarez      MX  16.8634  -99.8901        88
116             mukalla      YE  14.5425   49.1242        45
157         kailua-kona      US  19.6406 -155.9956        68
218      hafar al-batin      SA  28.4328   45.9708        30
291               macau      MO  22.2006  113.5461        68
296            anupgarh      IN  29.1911   73.2086        18
297              howrah      IN  22.5892   88.3103        38
348          saddiqabad      PK  28.3062   70.1307         9

### Step 4: For each city, use the Geoapify API to find the first hotel located within 10,000 metres of your coordinates.

In [10]:
# Set parameters to search for a hotel
radius = 10000
params = {
    "categories" : "accommodation.hotel",
    "limit" : 1,
    "apiKey" : geoapify_key,
    "radius" : radius
}

# Print a message to follow up the hotel search
print("Starting hotel search")

# Iterate through the hotel_df DataFrame
for index, row in hotel_df.iterrows():
    # get latitude, longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the current city's latitude and longitude to the params dictionary
    params["filter"] = f"circle:{lng},{lat},{radius}"
    params["bias"] = f"proximity:{lng},{lat}"

    # Set base URL
    base_url = "https://api.geoapify.com/v2/places"

    # Make and API request using the params dictionary
    name_address = requests.get(base_url,params=params)

    # Convert the API response to JSON format
    name_address = name_address.json()

    # Grab the first hotel from the results and store the name in the hotel_df DataFrame
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["features"][0]["properties"]["name"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No hotel found".
        hotel_df.loc[index, "Hotel Name"] = "No hotel found"

    # Log the search results
    print(f"{hotel_df.loc[index, 'City']} - nearest hotel: {hotel_df.loc[index, 'Hotel Name']}")

# Display sample data
hotel_df

Starting hotel search
east london - nearest hotel: No hotel found
acapulco de juarez - nearest hotel: Hotel del Valle
mukalla - nearest hotel: فندق الجابري
kailua-kona - nearest hotel: PACIFIC 19 Kona
hafar al-batin - nearest hotel: فندق توليب بلازا
macau - nearest hotel: 富華粵海酒店 Fu Hua Guang Dong Hotel
anupgarh - nearest hotel: Hotel Namish
howrah - nearest hotel: Sun India Guest House
saddiqabad - nearest hotel: No hotel found

,City,Country,Lat,Lng,Humidity,Hotel Name
22,east london,ZA,-33.0153,27.9116,57,No hotel found
69,acapulco de juarez,MX,16.8634,-99.8901,88,Hotel del Valle
116,mukalla,YE,14.5425,49.1242,45,فندق الجابري
157,kailua-kona,US,19.6406,-155.9956,68,PACIFIC 19 Kona
218,hafar al-batin,SA,28.4328,45.9708,30,فندق توليب بلازا
291,macau,MO,22.2006,113.5461,68,富華粵海酒店 Fu Hua Guang Dong Hotel
296,anupgarh,IN,29.1911,73.2086,18,Hotel Namish
297,howrah,IN,22.5892,88.3103,38,Sun India Guest House
348,saddiqabad,PK,28.3062,70.1307,9,No hotel found

### Step 5: Add the hotel name and the country as additional information in the hover message for each city in the map.

In [7]:
%%capture --no-display

# Configure the map plot
hotel_map = hotel_df.hvplot.points(
    x="Lng",
    y="Lat",
    size="Humidity",
    geo=True,
    tiles="OSM",
    color="City",
    alpha=0.6,
    width = 1000,
    height = 600,
    hover_cols=["City", "Country", "Humidity","Hotel Name"]  # Info to display on hover
)

# Display the map
# YOUR CODE HERE